### ISSUE TITLE
Don't require export of `package.json` file

### ISSUE THREAD

**Issue by piranna** [k-g-a/jest-node-exports-resolver#1] opened 2021-07-03 17:01 UTC
At https://github.com/k-g-a/jest-node-exports-resolver/blob/354697075045c2102e1b3934ae9f4634895b06d1/index.js#L25 dependency `package.json` file is required, that means it needs to be added to the `exports` field. Use it instead `require.resolve()` of the package itself, append `package.json` to the path, and require the file directly by hand to parse it.

**Comment by k-g-a** [comment] 2021-07-05 05:50
Thanks for the issue! Did not think of it, because we do export `package.json`'s from our own packages. I'll fix it withing a day.

**Comment by piranna** [comment] 2021-07-05 07:02
Great, thanks :-D

**Comment by k-g-a** [comment] 2021-07-05 10:59
It's actually not so easy to fix :) using `require.resolve(PACKAGE_NAME)` directly against a package with no "main" field specified (i.e. `@babel/runtime`) results in `ERR_PACKAGE_PATH_NOT_EXPORTED` error. So I'm going to combine both approaches. Could you please reference the package you're getting in trouble with so I could test solutions with it?

**Comment by piranna** [comment] 2021-07-05 11:33
> It's actually not so easy to fix :) using `require.resolve(PACKAGE_NAME)` directly against a package with no "main" field specified (i.e. `@babel/runtime`) results in `ERR_PACKAGE_PATH_NOT_EXPORTED` error.

Looks strange, specially since `require()` uses `require.resolve()` internally...


> Could you please reference the package you're getting in trouble with so I could test solutions with it?

It's currently a private one, but I can give you access to it.

**Comment by k-g-a** [comment] 2021-07-05 14:03
Just released v1.0.3 with fallback to `require.resolve()` in case of non-exported `package.json`, could you please check if the problem is fixed?

**Comment by k-g-a** [comment] 2021-07-06 17:30
Closing for now. Feel free to reopen if problem isn't fixed for your setup.

**Closed by k-g-a** 2021-07-06 17:30 UTC

**Comment by piranna** [comment] 2021-07-11 10:15
Hi @k-g-a, it seems at least for `jest` internal resolution of environment setup is not working. Must to admit, it's NOT the same use case I faced before, I'll try it later.

```js
Could not retrieve package.json neither through require (package.json itself is not within "exports" field), nor through require.resolve (package.json does not specify "main" field) - falling back to default resolver logic
Failed to find package.json for @mafalda/mafalda-api
● Validation Error:

  Module @mafalda/mafalda-api/expect in the setupFilesAfterEnv option was not found.
         <rootDir> is: /home/piranna/github/Mafalda/Mafalda

  Configuration Documentation:
  https://jestjs.io/docs/configuration
```

**Comment by k-g-a** [comment] 2021-07-12 08:18
Hi! 
Could you please try to replace `requestPath` with plain incoming `request` in `findMainPackageJson(requestPath, packageName)` at 57 line? If it works, I'll publish it as a fix.

But it's quite strange you face that error, because './package.json' *is exported* from your `mafalda/mafalda-api` pakcage.json's exports, so `packageJson = require(`${packageName}/package.json`);` should do it's work.

**Comment by piranna** [comment] 2021-07-12 19:10
With `package.json` entry it works, and both without it I get in latest published version or with your proposed change this error:

```js
Could not retrieve package.json neither through require (package.json itself is not within "exports" field), nor through require.resolve (package.json does not specify "main" field) - falling back to default resolver logic
```

**Comment by k-g-a** [comment] 2021-07-14 11:38
As far as I get it: everything works as expected if the package.json is exported, but neither 1.0.0 nor 1.0.3 work if not?

**Comment by piranna** [comment] 2021-07-14 12:08
Yes, that's it.

**Comment by piranna** [comment] 2021-07-25 17:10
With latest version, I can't import https://github.com/Mafalda-SFU/FsSet too without adding the `package.json` entry.

(Yes, `./` entry should be `.`, I have it already fixed)

**Comment by piranna** [comment] 2021-08-02 19:52
This also fails when the value of `exports` field is a string instead of a mapping object.
